version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
      - image: circleci/postgres:alpine
        environment:
          POSTGRES_PASSWORD: localdev
          POSTGRES_USER: contiamo_test
          POSTGRES_DB: postgres
    environment:
      GO111MODULE: "on"
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-cache
      - run:
          name: Install go tools
          command: |
            make setup-env
      - run:
          name: Print env
          command: make env
      - run:
          name: Verify formatting
          command: make fmt lint
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run unit tests
          command: make .test-ci
      - save_cache: # Store cache in the /go/pkg directory
          key: go-mod-cache
          paths:
            - "/go/pkg/mod"
