name: Test and Publish
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  # Label of the container job
  tests:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    env:
      default_branch: "refs/heads/main"

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: localdev
          POSTGRES_USER: contiamo_test
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: Determine Golang cache paths
        id: golang-path
        run: |
          echo "build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
          echo "module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
        shell: bash
      - name: Setup Golang cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.golang-path.outputs.build }}
            ${{ steps.golang-path.outputs.module }}
          key: ${{ runner.os }}-golang-contiamo-o-base-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-contiamo-go-base-
      - name: Print env
        run: make env
      - name: Format
        run: make fmt
      # use the action instead of make because it is slightly faster
      - name: Lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.50.1
      - name: Tests
        run: make .test-ci
        env:
          POSTGRES_PASSWORD: localdev
          POSTGRES_USER: contiamo_test
          POSTGRES_DB: postgres

  # we can use a separate job here because we don't have any post-release Docker steps
  release:
    needs: tests
    runs-on: ubuntu-latest
    env:
      default_branch: "refs/heads/main"
    steps:
      #####################
      # Release and Publish
      #####################
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        if: ${{ github.ref == env.default_branch }}
        with:
          # use the CI token to pretend not to be a action?
          # if this works then the resulting PRs will trigger
          # the test-build-publish
          token: ${{ secrets.CONTIAMO_CI_TOKEN }}
          release-type: go-yoshi
          package-name: ""
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"docs","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Miscellaneous","hidden":false}
            ]
