

name: 'Conventional commit titles'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize
      # When the title or description change
      - edited

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: deepakputhraya/action-pr-title@master
        with:
          # Ensure pull request titles match the Conventional Commits specification https://www.conventionalcommits.org/en/v1.0.0/
          # The optional scope is for a Jira ticket number (`CON-xxxx`)
          regex: '^(feat|fix|chore|ci|refactor|test)(\(CON-\d+\))?!?:'
