name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Format
      run: make fmt

    - name: Test
      env:
        GOPROXY: https://proxy.golang.org
      run: make test
